 tank:
  health: 25
  maxDistance: 4
 list:
   - basic
   - heavy
 details:
   basic:
      velocity: 5
      damage: 2
      ammo: 5
      name: "Basic Shot"
   heavy:
      velocity: 3
      damage: 4
      ammo: 2
      name: "Heavy Shot"